:PROPERTIES:
:ID: afeb0c3e-fca2-4cca-9da0-f6c50cfe4475
:END:

#+OPTIONS: todo:t tags:nil tasks:t ^:nil toc:nil
#+TODO: OPEN(y) (e) PROG(g) INTR(q) NEXT(n) | ABRT(a) DONE(f) CLSD(c)
#+FILETAGS: :topNote:typDev:catIssue:

* DONE Test Table Render :opTest:subOrgmode:
CLOSED: [2026-03-18 Wed 10:15]
:PROPERTIES:
:ID:       fe211ecb-ef53-41bd-9eb6-86d8873876a2
:END:
Testing =nvim-orgmode= table render \\

- Orgmode style:\\

| ID   | Name  | Phone | Age |
|------+-------+-------+-----|
| 19   | Peter | 1234  | 17  |
| 0880 | Anna  | 4321  | 25  |

- Markdown style: \\

| Header 1 | Header 2 | Header 3 |
|----------|----------|----------|
| Cell 1   | Cell 2   | Cell 3   |
| Cell 4   | Cell 5   | Cell 6   |
* DONE Orgmode Tag System Prefix :subOrgmode:opStructure:
CLOSED: [2026-03-18 Wed 10:15]
:PROPERTIES:
:ID:       fad7fd61-ac4d-4886-819e-f3acfdad2353
:END:
/Implement prefixes for tag system/
/Test:/  [[id:d95dff11-93ed-4f7b-9e6f-96c152127c2b][[TEST] Orgmode Tag Tests @test]]
** CLSD Tag Naming Technique
CLOSED: [2026-03-17 Tue 17:43]
:PROPERTIES:
:ID:       08b9ebef-b31d-4a2b-99fe-c0bc968065f1
:END:
Naming =tags= is like =naming variable=, There are different ways to name a tag. Determine which usage case is suitable for a tag
- [X] Camel Case (camelCase)
- [X] Pascal Case (PascalCase)
- [-] Snake Case (snake_case)
- [-] Kebab Case (kebab-case)
- [-] Upper Snake Case (UPPER_SNAKE_CASE)
- [X] *Hungarian Notation (strHungarianNotation)*
  + Plain text method
- [X] Abbreviation-Based Naming (abbr)

*Reference:*  [[https://dev.to/mutu/variable-naming-techniques-24hn][Variable naming techniques @Blog]]
*** CLSD Implement Symbol System :TEST_TAG:
CLOSED: [2026-03-18 Wed 08:17]
:PROPERTIES:
:ID:       7aed2570-be6d-4dd4-9566-ed2747fc55e6
:END:
#+name:LOGBOOK
#+html:<details><summary>LOGBOOK</summary>
:LOGBOOK:
- Note taken on [2026-03-18 Wed 08:15] \\
Special characters =#=, =%= breaks on github orgmode parser -> resort to plain text method
- Note taken on [2026-03-17 Tue 22:22] \\
Implement method:
- Using =sed= as search and replace operation
+ Run: =sed s/oldPattern/newPattern=
- Replace matching old tags with new tags patterns
:END:
#+html:</details>
Using =tag-system= prefix:
- =%=                 - as headline with fixed placeholder -> =%Tracker=
- =UPPCASE=           - as global topics -> =OPSYS=
- =_=                 - as category tags -> =_Planned=
- =lowercase=         - as headline sections -> =meta=
- =@=                 - Shared tags -> =@Nvim=
- =HungarianNotation= - as specific tag -> =NvimConfig=
  ! Not probably parsed =github=
*** CLSD Implement Plaintext Tag System
CLOSED: [2026-03-18 Wed 10:05]
:PROPERTIES:
:ID: 55bcb839-0b9f-4f7a-ba4b-a00f29d2f730
:END:
Plaintext Prefixes:
- =@= - for shared tag e.g. =@Nvim=
- =_= - for internal tag e.g. =_Nvim=
- =typ= - for type tag e.g. =typDoc=
- =cat= - for identifier tag e.g. =catOneoff=
- =HungarianNotation= - for specific tag e.g. =NvimConfig=
- =lowercase= - for special tag e.g. =noexport=, =meta=, =content=
* DONE Orgmode Tag Tests :opTest:subOrgmode:opStructure:
CLOSED: [2026-03-17 Tue 21:29]
:PROPERTIES:
:ID:       d95dff11-93ed-4f7b-9e6f-96c152127c2b
:END:
#+name:LOGBOOK
#+html:<details><summary>LOGBOOK</summary>
:LOGBOOK:
- Note taken on [2026-03-17 Tue 21:27] \\
  Failed on =github= and =orgzly= -> resort to plaintext method ([[id:08b9ebef-b31d-4a2b-99fe-c0bc968065f1][Hungarian Notation]])
:END:
#+html:</details>

#+name: Tags with false rencer
#+begin_quote markdown
[!WARNING]
This is an example of failed tags
#+end_quote

#+begin_src org
** CLSD Nvim-orgmode Test :FOOBAR:subnote:%tracker:#meta:opThis_is_a_headline:opIdentifier:
CLOSED: [2026-03-16 Mon 21:58]
:PROPERTIES:
:ID:       25848b1a-3eb5-4f3c-9755-0efb19bcb5e4
:END:
- [X] Treesitter grammar
- [X] Matching headline
- [X] Correctly Render
- [X] Following =org= syntax
** CLSD Orgzly Test :FOO:subNoteOrgzly:%tracker_orgzly:#meta_orgzly:opThis_is_a_headline:suborgzly:opidentifier:
CLOSED: [2026-03-16 Mon 22:34]
:PROPERTIES:
:ID:       83f55b3e-cf56-4900-be90-b8aae79c96ed
:END:
- [-] Headline Matching
-----
  - Note taken on [2026-03-16 22:31]: \\
    =orgzly= partially support =org-tag= syntax
    - =_= is treated as separator instead of a full tag (=_foo= is a child of =_foo_bar=)
-----
- [-] Differentiate between =uppercase= and =lowercase= tags
-----
  - Note taken on [2026-03-16 22:34]: \\
    =orgzly= matching method is "case-insensitive"
  -----
** CLSD Github Test :opgithub:oporgmode:
CLOSED: [2026-03-17 Tue 17:31]
:PROPERTIES:
:ID:       00758ee1-900e-418b-9fa7-cab4cb41b62c
:END:
=Snack_case= variable is not a valid syntax for a tag on github =org-ruby= parser. But =_= as prefix is valid e.g. =_foo= is a valid tag
#+end_src

* DONE Match and Remove :subBash:
CLOSED: [2026-03-18 Wed 20:18]
:PROPERTIES:
:ID: b6a92a84-88ad-468d-ad71-f10ba43d4cd9
:END:
/Removing matching pattern using cmdline/
#+BEGIN_SRC sh
rg -l  "\#\+LATEX_HEADER: \\\usepackage" /home/whammou/Journal/ | xargs -i sed -i '/^#+LATEX_HEADER:.*helvet/d' {}
#+END_SRC
* DONE Orgmode Snippets Refactor :subOrgmode:opRefactor:
CLOSED: [2026-06-16 Tue 22:34]
:PROPERTIES:
:ID: e733de64-736b-4ec7-99d9-f5904b87f476
:END:
- [X] /Refactor snippets db/
- [X] /Refactor snippets to include ID creation on new headline/
** DONE Trigger Character Conflict
CLOSED: [2026-03-24 Tue 02:07]
:PROPERTIES:
:ID: 184a34b1-9e01-4ae8-b92d-ef580c8f007d
:END:
/Only trigger snippets when there is a special character/
* DONE Reflow Note Repos :@Structure:subGit:subGit@Annex:
CLOSED: [2026-06-17 Wed 02:17]
:PROPERTIES:
:ID: ebbcd95c-3e9a-4ef0-b885-1b5d7f77d22f
:ROAM_ORIGIN: 038b7433-7aa0-425f-a718-0b1ef8fbc11f
:END:

#+name: Description
#+begin_quote org
Note should now lives act only as sub-repo for a bigger repo such as =workspace= repos
#+end_quote

#+name: Note Admonition - Description
#+begin_quote org
[!NOTE]
Changing from hierarchy-architect /(with sub-repos)/ to flat-architect /(without sub-repos)/ and manage files with =git-sync-rs= and populate and manage note repos with =populate= script
#+end_quote

The point of this architect is to make notes truly modular. Each note repo lives as an independent entity that can lives inside or along side any other *Workspace* architect

** DONE Sub-repo Manager :subGit@Manager:
CLOSED: [2026-06-17 Wed 02:22]
:PROPERTIES:
:ID: e4c2214b-4ae7-445e-a5d1-0bdbffef5694
:END:

#+name: Description
#+begin_quote org
Determine how should a number of note repos be updated? Manually and automatically. What architecture should be used for auto update repos
#+end_quote

Managing git repo with =populate= script which scrap =github= for matching repo /(with extension org)/ and auto populate the orgmode directory also update repo when existed /(cloned)/

#+name: poplulate-fragment
#+begin_src sh
#!/usr/bin/env bash
echo "  > Scanning github.com/$GITHUB_USER for note repos..." >&2

if command -v gh &>/dev/null && gh auth status &>/dev/null; then
  repos_json=$(gh repo list "$GITHUB_USER" --json name --limit 50 2>/dev/null)
elif command -v curl &>/dev/null; then
  repos_json=$(curl -sf "https://api.github.com/users/$GITHUB_USER/repos?per_page=100&sort=updated" 2>/dev/null)
else
  echo "Error: need gh (GitHub CLI) or curl to discover repos." >&2
  exit 1
fi
#+end_src
* DONE Get Notes on New Machine :@Initialization:
CLOSED: [2026-06-24 Wed 13:17]
:PROPERTIES:
:ID: 0ba0d6ca-80d2-444d-9fbd-b99a72ae0db0
:END:

#+name: Description
#+begin_quote org
How should new notes get initialized on new machine? Via
- Command line
- Shared Drive
- Hybrid system
#+end_quote

- [-] Using the command line:
  + Using command line like =git= to get the whole workspace
  + This method requires external tools like =git-annex=, =rclone=, =samba= to mount the drive and edit locally
  + Files are not allowed to be shared without credential

- [-] Share Drive method:
  + Using Share Drive to edit documents on e.g. =Google Drive= which has a built-in sharing mechanic
  + Requires external tools to mount and edit files
  + Files are not allowed to be shared without credential

- [X] Hybrid Method:
  + Clone workspace via =git=
  + Files are shared on external protocol like =webdav= /(with or without credential)/
  + Edit files via mounted drives e.g. =samba= /(or through webdav itself)/
  + Files are shared via URL /(more accessible)/
  + Cons: Complex and require a lot of setting ups
