:PROPERTIES:
:ID: 164e1f8a-7b45-403a-9c36-15f263f00eb5
:END:
#+TITLE: Individualize Notes

#+OPTIONS: title:nil tags:nil todo:nil ^:nil f:t num:t pri:nil toc:t
#+TODO: TODO(t) (e) DOIN(d) PEND(p) OUTL(o) EXPL(x) FDBK(b) WAIT(w) NEXT(n) IDEA(i) | ABRT(a) PRTL(r) RVIW(v) DONE(f)
#+FILETAGS: :typDoc:subProject:opLayout:
#+HTML:<details>

* RVIW Individualize Notes :typDoc:meta:opLayout:NOTE:
 DEADLINE: <2025-08-18 Mon> CLOSED: [2025-08-28 Thu 16:20]
#+HTML:</details>
- The key concept to =individualize notes= lies in the differences between =functionality= of each note and follow by their =layout format=
- Different types of note in the system serves different purposes and its important to get it clear what their purposes are
** DONE Define Functionality of Each Note
:PROPERTIES:
:ID: e8b1d7a4-e30c-4553-b3ea-bcd0b51a3bfb
:END:
CLOSED: [2025-08-09 Sat 02:30]
- Currently there are 4 types of note in the system
  1. =Doc notes=: Contain documents and export
  2. =List notes=: Contain reusable notes or items
  3. =Task notes=: Scheduling and planning tasks or events
  4. =Log notes=: Log =DONE=/=ABRT= tasks
** DONE Separating notes :NODE:
CLOSED: [2025-08-28 Thu 16:20]
:PROPERTIES:
:ID:       8c7144c1-eb8e-4985-b537-3293809b858c
:END:
The purpose of separating big notes into smaller notes is to create a /cleaner documentation/, /better organized and structured information/; /easier to share/
  + The =targets= of each notes have to be specifically formatted
  + Customized unique =templates= for each notes
  + Harder to maintenance
*** OUTL Milestone Note :subOrgmode@Structure:subProjectManagement:
:PROPERTIES:
:ID: 7d381283-8d6e-4542-bd57-10f2deddd4b9
:END:

#+name: Project milestone
#+begin_quote markdown
A project milestone is like a checkpoint on the road to completing a larger project. It breaks down a project into more manageable phases, helping you stay on track by highlighting key moments in the project’s timeline
#+end_quote

Milestone in project management give a broad view of progress and are made up of smaller specific actions like deadlines or individual tasks. Millstones serve as markers that signify when you've hit an important phase or achieved a major outcome, moving you close to the overall goal

#+name: Key Milestones in PM Examples
#+begin_quote markdown
[!TIP]
Project milestones vary depending on the type of project, but they all serve the same purpose:
- To track progress at key stages
- Ensure everything stays on course
#+end_quote

Next question is how to write a milestone note?
**** Writing a Milestone Note
:PROPERTIES:
:ID: 0880b906-06d3-4c25-a117-05d325fb002b
:END:

#+name: Writing Mileseon Step-by-step
#+begin_quote markdown
This is a step-by-step process to develop a stellar milestone report
#+end_quote

1. *Step 1:* Define the Purpose of the report \\

   Before Writing the report, identify its purpose. Are you updating stakeholders on the current progress? Highlighting challenges or risks? Requestion approval to move forward with the next phrase? Clarifying the propose helps structure you report to ensure it addresses the right questions and concerns \\

   Example: "/This report outlines the progress made in the website design project up to the wireframe completion milestone and addresses any remaining challenges before moving on to design approval/"

2. *Step 2:* Provide an Overview of the Project \\


